name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            cflags: ""
          - arch: i386
            cflags: "-m32"
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang clang-tidy make gcc-multilib g++-multilib python3 python3-pip
          pip3 install pre-commit
      - name: Build
        run: make CFLAGS="${{ matrix.cflags }}"
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: clang-tidy
        run: |
          clang-tidy --config-file=clang-tidy.config $(find . -name '*.c' -o -name '*.h') -- -std=c23 ${{ matrix.cflags }}
