name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: llvm/clang-format@v1
        with:
          style: file
          path: "**/*.{c,h}"
      - run: cmake -S . -B build -DCMAKE_C_STANDARD=23
      - run: cmake --build build
      - run: clang-tidy --config-file=clang-tidy.config $(find . -name '*.c' -o -name '*.h') -- -std=c23
