name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: llvm/clang-format@v1
        with:
          style: file
          path: "**/*.{c,h}"
      - name: Install dependencies
        run: ./setup.sh
      - run: make all CFLAGS+=' -std=c17 -Wall -Wextra -Wpedantic -Werror'
      - run: clang-tidy --config-file=clang-tidy.config $(find . -name '*.c' -o -name '*.h') -- -std=c17
